Repository LP23-1A/Team-2, pull requests merged in 2024-03, with the labels that each got.

#9 side bar
  client/package-lock.json
  client/package.json
  client/src/app/dashboard/page.tsx
  client/src/app/globals.css
  client/src/app/page.tsx
  client/src/components/Menu.tsx
  client/src/components/images/clipboard.png
  client/src/components/images/dashboard.png
  client/src/components/images/income.png
  client/src/components/images/product.png
  client/src/components/images/settings.png
Labels: enhancement

#10 feat navbar
  client/src/components/Navbar.tsx
  client/src/components/images/NavIcon.png
  client/src/components/images/bell.png
  client/src/components/images/user.png
Labels: enhancement

#14 admin folder nemsen
  client/src/app/admin/dashboard/page.tsx
  client/src/app/admin/income/page.tsx
  client/src/app/admin/order/page.tsx
  client/src/app/admin/product/page.tsx
  client/src/app/admin/settings/page.tsx
Labels: enhancement

#17 mongoDB connection
  server/src/utils/database.ts
Labels: enhancement

#19 admin path changes
  client/src/components/Menu.tsx
Labels: fix bug

#24 naming convention
  client/src/app/admin/signUp/page.tsx
  client/src/components/images/arrow.tsx
  server/src/controller/adminSign.ts
Labels: update

#25 12 feature income
  client/src/app/income/page.tsx
  client/src/components/images/Download.png
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/controller/order.ts
  server/src/index.ts
  server/src/model/order.ts
  server/src/router/order.ts
Labels: enhancement

#26 product map
  client/src/components/AddProduct.tsx
  client/src/components/Product.tsx
  client/src/components/ProductData.tsx
  server/src/index.ts
Labels: update

#28 design bolson
  client/src/app/admin/dashboard/page.tsx
  client/src/components/Menu.tsx
Labels: enhancement

#29 dashboard status
  client/package-lock.json
  client/package.json
  client/src/app/admin/dashboard/page.tsx
Labels: enhancement

#34 income section
  client/src/app/admin/income/page.tsx
  client/src/app/income/page.tsx
  server/src/controller/order.ts
  server/src/index.ts
  server/src/model/order.ts
  server/src/router/order.ts
Labels: enhancement

#36 35 feature order
  client/src/app/admin/order/page.tsx
  client/src/components/svg/Searchbar.tsx
  dasdasdasd
  server/src/controller/order.ts
  server/src/router/order.ts
Labels: enhancement

#42 add error show in screen
  client/src/app/admin/login/page.tsx
  client/src/app/page.tsx
  server/src/controller/product.ts
Labels: enhancement

#43 7 feature add product
  client/src/components/ProductData.tsx
  client/src/components/UpdateProduct.tsx
  server/src/controller/product.ts
Labels: enhancement

#44 add feature
  client/src/app/admin/login/page.tsx
  client/src/app/admin/signUp/page.tsx
Labels: enhancement

#46 ehnii chart backend holbson
  client/package-lock.json
  client/package.json
  client/src/app/admin/dashboard/@sales/page.tsx
  client/src/app/admin/dashboard/layout.tsx
  client/src/app/admin/dashboard/page.tsx
  client/src/components/Auth.tsx
  server/package-lock.json
Labels: enhancement

#51 50 sign bug
  client/package-lock.json
  client/package.json
  client/src/app/admin/addProduct/page.tsx
  client/src/app/admin/checkRole/page.tsx
  client/src/app/admin/income/page.tsx
  client/src/app/admin/login/page.tsx
  client/src/app/admin/order/orderdetails/page.tsx
  client/src/app/admin/order/page.tsx
  client/src/app/admin/signUp/page.tsx
  client/src/app/admin/updateProduct/page.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/components/AddProduct.tsx
  client/src/components/Auth.tsx
  client/src/components/ProductData.tsx
  client/src/components/ProductIMG.tsx
  client/src/components/UpdateProduct.tsx
  server/src/controller/adminSign.ts
  server/src/controller/order.ts
  server/src/controller/product.ts
  server/src/index.ts
  server/src/model/adminSign.ts
  server/src/model/order.ts
  server/src/model/product.ts
  server/src/router/adminSign.ts
  server/src/router/order.ts
  server/src/router/product.ts
Labels: bug

#58 48 update захиалга filter
  README.md
  client/package-lock.json
  client/package.json
  client/src/app/admin/income/page.tsx
  client/src/app/admin/order/page.tsx
  dasdasdasd
  server/dist/controller/adminSign.js
  server/dist/controller/dashboard.js
  server/dist/controller/order.js
  server/dist/controller/product.js
  server/dist/index.js
  server/dist/model/adminSign.js
  server/dist/model/order.js
  server/dist/model/product.js
  server/dist/router/adminSign.js
  server/dist/router/dashboard.js
  server/dist/router/order.js
  server/dist/router/product.js
  server/dist/utils/aws.js
  server/dist/utils/database.js
  server/src/controller/adminSign.ts
  server/src/controller/comment.ts
  server/src/controller/dashboard.ts
  server/src/controller/mainCategory.ts
  server/src/controller/order.ts
  server/src/controller/payment.ts
  server/src/controller/product.ts
  server/src/controller/review.ts
  server/src/controller/shoppingCart.ts
  server/src/controller/subCateogry.ts
  server/src/controller/user.ts
  server/src/index.ts
  server/src/model/comment.ts
  server/src/model/mainCategory.ts
  server/src/model/order.ts
  server/src/model/payment.ts
  server/src/model/product.ts
  server/src/model/review.ts
  server/src/model/shoppingCart.ts
  server/src/model/subCategory.ts
  server/src/model/user.ts
  server/src/router/ShoppingCart.ts
  server/src/router/comment.ts
  server/src/router/mainCategory.ts
  server/src/router/order.ts
  server/src/router/payment.ts
  server/src/router/product.ts
  server/src/router/review.ts
  server/src/router/subCategory.ts
  server/src/router/user.ts
Labels: update

#59 chart done
  client/package-lock.json
  client/package.json
  client/src/app/admin/dashboard/@sales/page.tsx
Labels: update

#61 code conflict fixed
  client/src/app/admin/order/page.tsx
  server/src/index.ts
Labels: update

#63 chart data displayed
  client/package-lock.json
  client/src/app/admin/dashboard/@sales/page.tsx
  client/src/app/admin/dashboard/page.tsx
  server/src/controller/order.ts
Labels: update

#65 47 feature product filter
  client/package-lock.json
  client/src/components/Product.tsx
  client/src/components/ProductData.tsx
  client/src/components/ProductFilter.tsx
  client/src/components/images/Calendar.tsx
  client/src/components/images/CategoryICON.tsx
  client/src/components/images/Dollar.tsx
Labels: enhancement

#55 add user interface login and sign
  client/src/app/admin/login/page.tsx
  client/src/app/admin/signUp/page.tsx
  client/src/app/globals.css
  client/src/app/page.tsx
  client/src/app/user/login/page.tsx
  client/src/app/user/sign/page.tsx
  server/src/controller/adminSign.ts
Labels: enhancement

#66 52 feature navbar and footer
  client/src/app/admin/order/page.tsx
  client/src/app/page.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/components/OrderList.tsx
  client/src/components/OrderNavbar.tsx
  client/src/components/svg/Allicons.tsx
  client/src/components/user/Footer.tsx
  client/src/components/user/HorizontalMenu.tsx
  client/src/components/user/Navbar.tsx
  server/src/controller/user.ts
  server/src/index.ts
  server/src/model/user.ts
  server/src/router/user.ts
Labels: enhancement

#70 68 check user email push to navbar
  client/package-lock.json
  client/package.json
  client/src/app/layout.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/app/user/login/page.tsx
  client/src/app/user/sign/page.tsx
  client/src/components/user/Navbar.tsx
  client/src/components/user/context.tsx
  server/src/controller/admin.ts
  server/src/router/adminSign.ts
Labels: enhancement

#73 add inf component
  client/src/components/user/AddInformation.tsx
Labels: enhancement

#74 67 best product
  client/src/app/admin/order/page.tsx
  client/src/app/user/[id]/page.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/app/user/productdetails/page.tsx
  client/src/components/OrderList.tsx
  client/src/components/svg/Allicons.tsx
  client/src/components/user/BestProduct.tsx
  client/src/components/user/BestProducts.tsx
  client/src/components/user/Footer.tsx
  client/src/components/user/Navbar.tsx
  client/src/components/user/Product.tsx
  package-lock.json
  package.json
  server/src/controller/order.ts
  server/src/controller/product.ts
  server/src/router/order.ts
  server/src/router/product.ts
Labels: enhancement

#75 7 feature add product
  client/package-lock.json
  client/src/app/admin/product/page.tsx
  client/src/components/AddProduct.tsx
  client/src/components/Aws.tsx
  client/src/components/Product.tsx
  client/src/components/ProductData.tsx
  client/src/components/ProductFilter.tsx
  client/src/components/ProductIMG.tsx
  client/src/components/UpdateProduct.tsx
  server/package-lock.json
  server/package.json
  server/src/controller/product.ts
  server/src/controller/subCategory.ts
  server/src/router/aws.ts
  server/src/router/subCategory.ts
  server/src/utils/aws.ts
Labels: update

#76 71 user interface product
  client/src/app/admin/product/page.tsx
  client/src/app/globals.css
  client/src/app/user/dashboard/page.tsx
  client/src/components/user/Product.tsx
Labels: enhancement

#81 new product baaztai holbogdov
  client/src/app/user/dashboard/page.tsx
  client/src/components/svg/Allicons.tsx
  client/src/components/user/BestProduct.tsx
  client/src/components/user/BestProducts.tsx
  client/src/components/user/Navbar.tsx
  client/src/components/user/NewProduct.tsx
  client/src/components/user/Product.tsx
Labels: update

#83 53 feature carousel
  client/package-lock.json
  client/package.json
  client/src/app/page.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/components/images/sandal.png
  client/src/components/user/Carousel.tsx
  client/src/components/user/CarouselMain.tsx
  client/src/components/user/Footer.tsx
  client/src/components/user/HorizontalMenu.tsx
  client/src/components/user/Navbar.tsx
Labels: enhancement

#85 78 feature contact information
  client/package-lock.json
  client/package.json
  client/src/app/user/DeliveryInf/page.tsx
  client/src/components/user/ContactData.tsx
  client/src/components/user/ContactInf.tsx
Labels: enhancement

#87 53 feature carousel
  client/src/app/user/dashboard/page.tsx
  client/src/components/user/Carousel.tsx
  client/src/components/user/CarouselMain.tsx
  client/src/components/user/Navbar.tsx
Labels: update

#89 82 order details
  client/package-lock.json
  client/package.json
  client/src/app/admin/[id]/page.tsx
  client/src/app/admin/order/page.tsx
  client/src/app/user/[id]/page.tsx
  client/src/components/OrderList.tsx
  client/src/components/user/BestProduct.tsx
  server/src/controller/order.ts
  server/src/router/order.ts
Labels: enhancement

#90 carousel bolson
  client/src/components/user/CarouselMain.tsx
Labels: update

#91 sign bug edited
  client/src/app/admin/signUp/page.tsx
  client/src/app/user/login/page.tsx
Labels: bug

#92 test
  client/src/components/user/CarouselMain.tsx
Labels: update

#94 carousel database zurag awdag bolson
  client/src/app/user/dashboard/page.tsx
  client/src/components/user/Carousel.tsx
  client/src/components/user/CarouselMain.tsx
Labels: update

#95 design fix perfect
  client/src/app/page.tsx
  client/src/app/user/dashboard/page.tsx
  client/src/components/user/AddInformation.tsx
  client/src/components/user/BestProducts.tsx
  client/src/components/user/Footer.tsx
  client/src/components/user/HorizontalMenu.tsx
  client/src/components/user/Navbar.tsx
Labels: bug

#96 84 product cartand nemeh
  client/package-lock.json
  client/package.json
  client/src/app/admin/order/page.tsx
  client/src/app/layout.tsx
  client/src/app/user/Cart/page.tsx
  client/src/app/user/[id]/page.tsx
  client/src/components/OrderList.tsx
  client/src/components/svg/Allicons.tsx
  client/src/components/user/BestProducts.tsx
  client/src/components/user/Footer.tsx
  client/src/components/user/Navbar.tsx
  client/src/components/user/NewProduct.tsx
  client/src/components/user/ProductContext.tsx
  server/src/controller/order.ts
  server/src/model/order.ts
Labels: update

#98 add docker file
  server/Dockerfile
  server/src/index.ts
Labels: enhancement

#101 88 feature client menu
  client/package-lock.json
  client/package.json
  client/src/app/page.tsx
  client/src/app/user/AllProducts/page.tsx
  client/src/components/user/AllProduct.tsx
  client/src/components/user/Navbar.tsx
  client/tsconfig.json
Labels: enhancement

#103 102 order product
  client/src/app/layout.tsx
  client/src/app/user/Cart/page.tsx
  client/src/app/user/DeliveryInf/page.tsx
  client/src/components/user/BestProduct.tsx
  client/src/components/user/BestProducts.tsx
  client/src/components/user/CarouselMain.tsx
  client/src/components/user/ContactData.tsx
  client/src/components/user/ContactInf.tsx
  client/src/components/user/Navbar.tsx
  client/src/components/user/NewProduct.tsx
  client/src/components/user/ProductContext.tsx
  client/src/components/user/UserOrderProvider.tsx
  server/src/controller/order.ts
  server/src/model/order.ts
Labels: update
